Cherry pick GDB-10007 - Set params on every query POST request (#205) (#206)
* GDB-10007 - Set params on every query POST request (#205)

* GDB-10007 - set params on every request

* GDB-10007 - modify expected requests in tests

(cherry picked from commit 40f3524ee49da82c74b9a6a2b10030510e3e2c8d)

GDB-10007 - generate new docs

* Update sonarqube-scanner to prevent errors during the sonar scanning step on CI
```
java.lang.UnsupportedClassVersionError: org/sonar/batch/bootstrapper/EnvironmentInformation has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0```

recreated package-lock file

---------

Co-authored-by: svilen.velikov <svilen.velikov@ontotext.com>